const SHOW_NAV_DROPDOWN = 'SHOW_NAV_DROPDOWN';
const HIDE_NAV_DROPDOWN = 'HIDE_NAV_DROPDOWN';

const GET_USER_INFO = 'GET_USER_INFO';

export {
  SHOW_NAV_DROPDOWN,
  HIDE_NAV_DROPDOWN,
  GET_USER_INFO,
};
