const SHOW_NAV_DROPDOWN = 'SHOW_NAV_DROPDOWN';
const HIDE_NAV_DROPDOWN = 'HIDE_NAV_DROPDOWN';

const SET_USER_NAME = 'SET_USER_NAME';
const CLEAR_USER_NAME = 'CLEAR_USER_NAME';
// const GET_USER_NAME = 'GET_USER_NAME';

export {
  SHOW_NAV_DROPDOWN,
  HIDE_NAV_DROPDOWN,
  SET_USER_NAME,
  CLEAR_USER_NAME,
  // GET_USER_NAME,
};
