const SHOW_NAV_DROPDOWN = 'SHOW_NAV_DROPDOWN';
const HIDE_NAV_DROPDOWN = 'HIDE_NAV_DROPDOWN';
// user
const SET_USER_NAME = 'SET_USER_NAME';
const CLEAR_USER_NAME = 'CLEAR_USER_NAME';
// const GET_USER_NAME = 'GET_USER_NAME';

// news
const SET_NEWS_LIST = 'SET_NEWS_LIST';
const SET_NEWS_TOTAL = 'SET_NEWS_TOTAL';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export {
  SHOW_NAV_DROPDOWN,
  HIDE_NAV_DROPDOWN,
  SET_USER_NAME,
  CLEAR_USER_NAME,
  SET_NEWS_LIST,
  SET_NEWS_TOTAL,
  SET_CURRENT_PAGE,
};
